apiVersion: apps/v1
kind: Deployment
metadata:
  name: party-card-server
  namespace: party-card-game
  labels:
    app: party-card-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: party-card-server
  template:
    metadata:
      labels:
        app: party-card-server
    spec:
      containers:
        - name: server
          image: party-card-game-server:1.1 # Image must be available in K3s (docker import or pull from registry)
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
# No resource limits for now, but good practice to add them later.

---
apiVersion: v1
kind: Service
metadata:
  name: party-card-server
  namespace: party-card-game
spec:
  selector:
    app: party-card-server
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
